"""Script templates for ContextCore installation.

Generates platform-appropriate installation scripts:
- Bash scripts for macOS/Linux
- PowerShell scripts for Windows
"""

import sys
from datetime import datetime
from typing import Optional

__all__ = ["render_docker_compose_script", "render_kind_script", "render_custom_script"]


# =============================================================================
# Bash Templates (macOS / Linux)
# =============================================================================

DOCKER_COMPOSE_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Docker Compose
set -e

echo "=== ContextCore Installation ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
VENV_PATH="{venv_path}"
{env_exports}
# Navigate to project
cd "$PROJECT_DIR"

# Create virtual environment if needed
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Install ContextCore
echo "Installing ContextCore..."
pip install -e ".[dev]"

# Deploy observability stack
echo "Deploying observability stack..."
make full-setup

# Verify installation
echo "Verifying installation..."
contextcore install verify

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: ${{GRAFANA_URL:-http://localhost:3000}}/d/contextcore-installation"
'''


KIND_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Kind Cluster
set -e

echo "=== ContextCore Installation (Kind) ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
DEPLOY_DIR="{deploy_dir}"
VENV_PATH="{venv_path}"
CLUSTER_NAME="{cluster_name}"
{env_exports}
# Check for kind
if ! command -v kind &> /dev/null; then
    echo "Error: kind not found. Please install kind first."
    echo "See: https://kind.sigs.k8s.io/docs/user/quick-start/#installation"
    exit 1
fi

# Create Kind cluster if it doesn't exist
if ! kind get clusters | grep -q "^$CLUSTER_NAME$"; then
    echo "Creating Kind cluster: $CLUSTER_NAME"
    kind create cluster --name "$CLUSTER_NAME"
else
    echo "Kind cluster '$CLUSTER_NAME' already exists"
fi

# Set kubectl context
kubectl cluster-info --context "kind-$CLUSTER_NAME"

# Install ContextCore CLI
cd "$PROJECT_DIR"
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi
source "$VENV_PATH/bin/activate"
pip install -e ".[dev]"

# Deploy observability stack to cluster
echo "Deploying observability stack to Kind cluster..."
kubectl apply -k k8s/observability/ || echo "Note: k8s manifests may need customization"

# Wait for services
echo "Waiting for services to be ready..."
kubectl wait --for=condition=ready pod -l app=grafana --timeout=120s || true

# Verify installation
echo "Verifying installation..."
contextcore install verify --endpoint localhost:4317

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: http://localhost:3000/d/contextcore-installation"
echo "Note: You may need to port-forward Grafana: kubectl port-forward svc/grafana 3000:3000"
'''


CUSTOM_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Custom (existing infrastructure)
set -e

echo "=== ContextCore Installation (Custom) ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
VENV_PATH="{venv_path}"
{env_exports}
# Navigate to project
cd "$PROJECT_DIR"

# Create virtual environment if needed
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Install ContextCore
echo "Installing ContextCore..."
pip install -e ".[dev]"

# Verify connection to existing infrastructure
echo "Verifying connection to infrastructure..."
contextcore install verify

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: ${{GRAFANA_URL:-http://localhost:3000}}/d/contextcore-installation"
echo ""
echo "Note: This script assumes your observability infrastructure is already running."
echo "Make sure the following services are accessible:"
echo "  - Grafana: $GRAFANA_URL"
echo "  - OTLP Endpoint: $OTEL_EXPORTER_OTLP_ENDPOINT"
'''


# =============================================================================
# PowerShell Templates (Windows)
# =============================================================================

PS_DOCKER_COMPOSE_TEMPLATE = '''# ContextCore Installation Script
# Generated: {timestamp}
# Method: Docker Compose
$ErrorActionPreference = "Stop"

Write-Host "=== ContextCore Installation ==="
Write-Host "Generated by: contextcore tui script-generator"
Write-Host ""

# Configuration
$ProjectDir = "{project_dir}"
$VenvPath = "{venv_path}"
{env_exports}
# Navigate to project
Set-Location $ProjectDir

# Create virtual environment if needed
if (-not (Test-Path $VenvPath)) {{
    Write-Host "Creating virtual environment..."
    python -m venv $VenvPath
}}

# Activate virtual environment
& "$VenvPath\\Scripts\\Activate.ps1"

# Install ContextCore
Write-Host "Installing ContextCore..."
pip install -e ".[dev]"

# Deploy observability stack
Write-Host "Deploying observability stack..."
docker compose -f docker-compose.yaml up -d

# Wait for services
Write-Host "Waiting for services to be ready..."
$timeout = 60
$elapsed = 0
while ($elapsed -lt $timeout) {{
    try {{
        $null = Invoke-WebRequest -Uri "http://localhost:3000/api/health" -UseBasicParsing -TimeoutSec 2
        break
    }} catch {{
        Start-Sleep -Seconds 2
        $elapsed += 2
    }}
}}

# Verify installation
Write-Host "Verifying installation..."
contextcore install verify

Write-Host ""
Write-Host "=== Installation Complete ==="
$grafanaUrl = if ($env:GRAFANA_URL) {{ $env:GRAFANA_URL }} else {{ "http://localhost:3000" }}
Write-Host "Dashboard: $grafanaUrl/d/contextcore-installation"
'''


PS_KIND_TEMPLATE = '''# ContextCore Installation Script
# Generated: {timestamp}
# Method: Kind Cluster
$ErrorActionPreference = "Stop"

Write-Host "=== ContextCore Installation (Kind) ==="
Write-Host "Generated by: contextcore tui script-generator"
Write-Host ""

# Configuration
$ProjectDir = "{project_dir}"
$DeployDir = "{deploy_dir}"
$VenvPath = "{venv_path}"
$ClusterName = "{cluster_name}"
{env_exports}
# Check for kind
if (-not (Get-Command kind -ErrorAction SilentlyContinue)) {{
    Write-Host "Error: kind not found. Please install kind first."
    Write-Host "See: https://kind.sigs.k8s.io/docs/user/quick-start/#installation"
    exit 1
}}

# Create Kind cluster if it doesn't exist
$clusters = kind get clusters 2>&1
if ($clusters -notcontains $ClusterName) {{
    Write-Host "Creating Kind cluster: $ClusterName"
    kind create cluster --name $ClusterName
}} else {{
    Write-Host "Kind cluster '$ClusterName' already exists"
}}

# Set kubectl context
kubectl cluster-info --context "kind-$ClusterName"

# Install ContextCore CLI
Set-Location $ProjectDir
if (-not (Test-Path $VenvPath)) {{
    Write-Host "Creating virtual environment..."
    python -m venv $VenvPath
}}
& "$VenvPath\\Scripts\\Activate.ps1"
pip install -e ".[dev]"

# Deploy observability stack to cluster
Write-Host "Deploying observability stack to Kind cluster..."
kubectl apply -k k8s/observability/

# Wait for services
Write-Host "Waiting for services to be ready..."
kubectl wait --for=condition=ready pod -l app=grafana --timeout=120s

# Verify installation
Write-Host "Verifying installation..."
contextcore install verify --endpoint localhost:4317

Write-Host ""
Write-Host "=== Installation Complete ==="
Write-Host "Dashboard: http://localhost:3000/d/contextcore-installation"
Write-Host "Note: You may need to port-forward Grafana: kubectl port-forward svc/grafana 3000:3000"
'''


PS_CUSTOM_TEMPLATE = '''# ContextCore Installation Script
# Generated: {timestamp}
# Method: Custom (existing infrastructure)
$ErrorActionPreference = "Stop"

Write-Host "=== ContextCore Installation (Custom) ==="
Write-Host "Generated by: contextcore tui script-generator"
Write-Host ""

# Configuration
$ProjectDir = "{project_dir}"
$VenvPath = "{venv_path}"
{env_exports}
# Navigate to project
Set-Location $ProjectDir

# Create virtual environment if needed
if (-not (Test-Path $VenvPath)) {{
    Write-Host "Creating virtual environment..."
    python -m venv $VenvPath
}}

# Activate virtual environment
& "$VenvPath\\Scripts\\Activate.ps1"

# Install ContextCore
Write-Host "Installing ContextCore..."
pip install -e ".[dev]"

# Verify connection to existing infrastructure
Write-Host "Verifying connection to infrastructure..."
contextcore install verify

Write-Host ""
Write-Host "=== Installation Complete ==="
$grafanaUrl = if ($env:GRAFANA_URL) {{ $env:GRAFANA_URL }} else {{ "http://localhost:3000" }}
Write-Host "Dashboard: $grafanaUrl/d/contextcore-installation"
Write-Host ""
Write-Host "Note: This script assumes your observability infrastructure is already running."
Write-Host "Make sure the following services are accessible:"
Write-Host "  - Grafana: $($env:GRAFANA_URL)"
Write-Host "  - OTLP Endpoint: $($env:OTEL_EXPORTER_OTLP_ENDPOINT)"
'''


# =============================================================================
# Rendering Helpers
# =============================================================================

def _format_env_exports_bash(
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
    include_defaults: bool = False,
) -> str:
    """Format environment variable exports for bash."""
    env_lines = []
    if grafana_url:
        env_lines.append(f'export GRAFANA_URL="{grafana_url}"')
    elif include_defaults:
        env_lines.append('export GRAFANA_URL="http://localhost:3000"')
    if otel_endpoint:
        env_lines.append(f'export OTEL_EXPORTER_OTLP_ENDPOINT="{otel_endpoint}"')
    elif include_defaults:
        env_lines.append('export OTEL_EXPORTER_OTLP_ENDPOINT="localhost:4317"')
    return '\n'.join(env_lines) + '\n' if env_lines else ''


def _format_env_exports_ps(
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
    include_defaults: bool = False,
) -> str:
    """Format environment variable exports for PowerShell."""
    env_lines = []
    if grafana_url:
        env_lines.append(f'$env:GRAFANA_URL = "{grafana_url}"')
    elif include_defaults:
        env_lines.append('$env:GRAFANA_URL = "http://localhost:3000"')
    if otel_endpoint:
        env_lines.append(f'$env:OTEL_EXPORTER_OTLP_ENDPOINT = "{otel_endpoint}"')
    elif include_defaults:
        env_lines.append('$env:OTEL_EXPORTER_OTLP_ENDPOINT = "localhost:4317"')
    return '\n'.join(env_lines) + '\n' if env_lines else ''


def _is_windows() -> bool:
    """Check if the current platform is Windows."""
    return sys.platform == "win32"


# =============================================================================
# Public Render Functions
# =============================================================================

def render_docker_compose_script(
    project_dir: str = ".",
    venv_path: str = ".venv",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render Docker Compose installation script.

    Generates a bash script on macOS/Linux and a PowerShell script on Windows.

    Args:
        project_dir: Path to the ContextCore project directory
        venv_path: Path to virtual environment (relative to project_dir)
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered installation script for the current platform
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if _is_windows():
        env_exports = _format_env_exports_ps(grafana_url, otel_endpoint)
        return PS_DOCKER_COMPOSE_TEMPLATE.format(
            timestamp=timestamp,
            project_dir=project_dir,
            venv_path=venv_path,
            env_exports=env_exports,
        )

    env_exports = _format_env_exports_bash(grafana_url, otel_endpoint)
    return DOCKER_COMPOSE_TEMPLATE.format(
        timestamp=timestamp,
        project_dir=project_dir,
        venv_path=venv_path,
        env_exports=env_exports,
    )


def render_kind_script(
    project_dir: str = ".",
    deploy_dir: str = "./deploy/kind",
    venv_path: str = ".venv",
    cluster_name: str = "wayfinder-dev",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render Kind cluster installation script.

    Generates a bash script on macOS/Linux and a PowerShell script on Windows.

    Args:
        project_dir: Path to the ContextCore project directory
        deploy_dir: Path to deployment directory (for cluster scripts)
        venv_path: Path to virtual environment (relative to project_dir)
        cluster_name: Name for the Kind cluster
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered installation script for the current platform
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if _is_windows():
        env_exports = _format_env_exports_ps(grafana_url, otel_endpoint)
        return PS_KIND_TEMPLATE.format(
            timestamp=timestamp,
            project_dir=project_dir,
            deploy_dir=deploy_dir,
            venv_path=venv_path,
            cluster_name=cluster_name,
            env_exports=env_exports,
        )

    env_exports = _format_env_exports_bash(grafana_url, otel_endpoint)
    return KIND_TEMPLATE.format(
        timestamp=timestamp,
        project_dir=project_dir,
        deploy_dir=deploy_dir,
        venv_path=venv_path,
        cluster_name=cluster_name,
        env_exports=env_exports,
    )


def render_custom_script(
    project_dir: str = ".",
    venv_path: str = ".venv",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render custom infrastructure installation script.

    Generates a bash script on macOS/Linux and a PowerShell script on Windows.

    Args:
        project_dir: Path to the ContextCore project directory
        venv_path: Path to virtual environment (relative to project_dir)
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered installation script for the current platform
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if _is_windows():
        env_exports = _format_env_exports_ps(
            grafana_url, otel_endpoint, include_defaults=True,
        )
        return PS_CUSTOM_TEMPLATE.format(
            timestamp=timestamp,
            project_dir=project_dir,
            venv_path=venv_path,
            env_exports=env_exports,
        )

    env_exports = _format_env_exports_bash(
        grafana_url, otel_endpoint, include_defaults=True,
    )
    return CUSTOM_TEMPLATE.format(
        timestamp=timestamp,
        project_dir=project_dir,
        venv_path=venv_path,
        env_exports=env_exports,
    )
